---
gemAuthor: MX
gemAuthorEmail: devexperience@mx.com
gemDescription: A Ruby library for the MX Platform API.
gemHomepage: https://github.com/mxenabled/mx-platform-ruby
gemLicense: MIT
gemName: mx-platform-ruby
gemRequiredRubyVersion: ">= 2.6"
gemVersion: 0.30.0
library: faraday
moduleName: MxPlatformRuby
