=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

The version of the OpenAPI document: 20111101

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MxPlatformRuby::MerchantsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MerchantsApi' do
  before do
    # run before each test
    @api_instance = MxPlatformRuby::MerchantsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MerchantsApi' do
    it 'should create an instance of MerchantsApi' do
      expect(@api_instance).to be_instance_of(MxPlatformRuby::MerchantsApi)
    end
  end

  # unit tests for list_merchants
  # List merchants
  # This endpoint returns a paginated list of all the merchants in the MX system.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name This will list only merchants in which the appended string appears.
  # @option opts [Integer] :page Results are paginated. Specify current page.
  # @option opts [Integer] :records_per_page This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead.
  # @return [MerchantsResponseBody]
  describe 'list_merchants test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for read_merchant
  # Read merchant
  # Returns information about a particular merchant, such as a logo, name, and website.
  # @param merchant_guid The unique id for a &#x60;merchant&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [MerchantResponseBody]
  describe 'read_merchant test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for read_merchant_location
  # Read merchant location
  # This endpoint returns the specified &#x60;merchant_location&#x60; resource. The &#x60;merchant_location_guid&#x60; can be found on &#x60;transaction&#x60; objects.
  # @param merchant_location_guid The unique id for a &#x60;merchant_location&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [MerchantLocationResponseBody]
  describe 'read_merchant_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
