=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

The version of the OpenAPI document: 20111101

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MxPlatformRuby::MonthlyCashFlowProfileApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MonthlyCashFlowProfileApi' do
  before do
    # run before each test
    @api_instance = MxPlatformRuby::MonthlyCashFlowProfileApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MonthlyCashFlowProfileApi' do
    it 'should create an instance of MonthlyCashFlowProfileApi' do
      expect(@api_instance).to be_instance_of(MxPlatformRuby::MonthlyCashFlowProfileApi)
    end
  end

  # unit tests for read_monthly_cash_flow_profile
  # Read monthly cash flow profile
  # Read monthly cash flow profile.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [MonthlyCashFlowResponseBody]
  describe 'read_monthly_cash_flow_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_monthly_cash_flow_profile
  # Update monthly cash flow profile
  # Use this endpoint to update the attributes of a &#x60;monthly_cash_flow_profile&#x60;.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param monthly_cash_flow_profile_request_body 
  # @param [Hash] opts the optional parameters
  # @return [MonthlyCashFlowResponseBody]
  describe 'update_monthly_cash_flow_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
