=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

The version of the OpenAPI document: 20111101

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MxPlatformRuby::ProcessorTokenApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProcessorTokenApi' do
  before do
    # run before each test
    @api_instance = MxPlatformRuby::ProcessorTokenApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProcessorTokenApi' do
    it 'should create an instance of ProcessorTokenApi' do
      expect(@api_instance).to be_instance_of(MxPlatformRuby::ProcessorTokenApi)
    end
  end

  # unit tests for check_real_time_account_balance
  # Check Real Time Account Balance (Processors Only)
  # Check the real-time account balance using your access token.
  # @param [Hash] opts the optional parameters
  # @return [MemberResponseBody]
  describe 'check_real_time_account_balance test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for deprecated_request_payment_processor_authorization_code
  # (Deprecated) Request an authorization code
  # (This endpoint is deprecated. Clients should use &#x60;/authorization_code&#x60;.) Clients use this endpoint to request an authorization_code according to a user, member, and account specified in the request body. Clients then pass this code to processors. Processor access is scoped only to the user/member/account specified in this request. Before requesting an authorization_code, clients must have verified the specified member.
  # @param payment_processor_authorization_code_request_body The scope for the authorization code.
  # @param [Hash] opts the optional parameters
  # @return [PaymentProcessorAuthorizationCodeResponseBody]
  describe 'deprecated_request_payment_processor_authorization_code test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_account_owner_info
  # Get account owner information (Processors Only)
  # Get account owner information (Processors Only)
  # @param [Hash] opts the optional parameters
  # @return [ProcessorOwnerBody]
  describe 'get_account_owner_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_tokens
  # View a List of Tokens
  # View a list of tokens that exist for a user, member, or account.
  # @param [Hash] opts the optional parameters
  # @option opts [TokenRequestBody] :token_request_body 
  # @return [TokenResponseBody]
  describe 'list_tokens test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for read_account_balance
  # Read the account balance (Processors Only)
  # Read the account balance (Processors Only)
  # @param [Hash] opts the optional parameters
  # @return [PaymentAccountBody]
  describe 'read_account_balance test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for request_account_number
  # Request an account number (Processors Only)
  # Get account information such as routing number and account number, scoped to your access token.
  # @param [Hash] opts the optional parameters
  # @return [ProcessorAccountNumberBody]
  describe 'request_account_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for request_authorization_code
  # Request an authorization code
  # Clients use this endpoint to request an authorization code according to the parameters specified in the scope. Clients then pass this code to processors. Processor access is scoped only to the GUIDs and features specified in this request. Before requesting an authorization code which includes a member in the scope, clients must have verified that member.
  # @param authorization_code_request_body The scope for the authorization code.
  # @param [Hash] opts the optional parameters
  # @return [AuthorizationCodeResponseBody]
  describe 'request_authorization_code test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
