=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

The version of the OpenAPI document: 20111101

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MxPlatformRuby::RewardsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RewardsApi' do
  before do
    # run before each test
    @api_instance = MxPlatformRuby::RewardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RewardsApi' do
    it 'should create an instance of RewardsApi' do
      expect(@api_instance).to be_instance_of(MxPlatformRuby::RewardsApi)
    end
  end

  # unit tests for credit_card
  # Read a Credit Card Product
  # This endpoint returns the specified &#x60;credit_card_product&#x60; according to the unique GUID.
  # @param credit_card_product_guid The required &#x60;credit_card_product_guid&#x60; can be found on the &#x60;account&#x60; object.
  # @param [Hash] opts the optional parameters
  # @return [CreditCardProductResponse]
  describe 'credit_card test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for fetch_rewards
  # Fetch Rewards
  # Calling this endpoint initiates an aggregation-type event which will gather the member&#39;s rewards information, as well as account and transaction information. Rewards data is also gathered with daily background aggregations. Member and Rewards guids are defined by MX.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param member_guid The unique id for a &#x60;member&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [MemberResponseBody]
  describe 'fetch_rewards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_rewards
  # List Rewards
  # Use this endpoint to list all the &#x60;rewards&#x60; associated with a specified &#x60;member&#x60;. Member guids are defined by MX.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param member_guid The unique id for a &#x60;member&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [RewardsResponseBody]
  describe 'list_rewards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for read_rewards
  # Read Reward
  # Use this endpoint to read a specific &#x60;reward&#x60; based on its unique GUID. Member and Rewards guids are defined by MX.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param member_guid The unique id for a &#x60;member&#x60;.
  # @param reward_guid The unique identifier for the rewards. Defined by MX.
  # @param [Hash] opts the optional parameters
  # @return [RewardResponseBody]
  describe 'read_rewards test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
