=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

The version of the OpenAPI document: 20111101

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MxPlatformRuby::StatementsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StatementsApi' do
  before do
    # run before each test
    @api_instance = MxPlatformRuby::StatementsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatementsApi' do
    it 'should create an instance of StatementsApi' do
      expect(@api_instance).to be_instance_of(MxPlatformRuby::StatementsApi)
    end
  end

  # unit tests for download_statement_pdf
  # Download statement pdf
  # Use this endpoint to download a specified statement PDF.
  # @param member_guid The unique id for a &#x60;member&#x60;.
  # @param statement_guid The unique id for a &#x60;statement&#x60;.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'download_statement_pdf test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for fetch_statements
  # Fetch statements
  # Use this endpoint to fetch the statements associated with a particular member.
  # @param member_guid The unique id for a &#x60;member&#x60;.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [MemberResponseBody]
  describe 'fetch_statements test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_statements_by_member
  # List statements by member
  # Use this endpoint to get an array of available statements.
  # @param member_guid The unique id for a &#x60;member&#x60;.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Results are paginated. Specify current page.
  # @option opts [Integer] :records_per_page This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead.
  # @return [StatementsResponseBody]
  describe 'list_statements_by_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for read_statement_by_member
  # Read statement by member
  # Use this endpoint to read a JSON representation of the statement.
  # @param member_guid The unique id for a &#x60;member&#x60;.
  # @param statement_guid The unique id for a &#x60;statement&#x60;.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [StatementResponseBody]
  describe 'read_statement_by_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
