=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

The version of the OpenAPI document: 20111101

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MxPlatformRuby::TagsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TagsApi' do
  before do
    # run before each test
    @api_instance = MxPlatformRuby::TagsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TagsApi' do
    it 'should create an instance of TagsApi' do
      expect(@api_instance).to be_instance_of(MxPlatformRuby::TagsApi)
    end
  end

  # unit tests for create_tag
  # Create tag
  # Use this endpoint to create a new custom tag.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param tag_create_request_body Tag object to be created with required parameters (tag_guid)
  # @param [Hash] opts the optional parameters
  # @return [TagResponseBody]
  describe 'create_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_tag
  # Delete tag
  # Use this endpoint to permanently delete a specific tag based on its unique GUID. If successful, the API will respond with status of &#x60;204 No Content&#x60;.
  # @param tag_guid The unique id for a &#x60;tag&#x60;.
  # @param accept Specifies the media type expected in the response.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_tags
  # List tags
  # Use this endpoint to list all tags associated with the specified &#x60;user&#x60;. Each user includes the &#x60;Business&#x60; tag by default.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Results are paginated. Specify current page.
  # @option opts [Integer] :records_per_page This specifies the number of records to be returned on each page. Defaults to &#x60;25&#x60;. The valid range is from &#x60;10&#x60; to &#x60;1000&#x60;. If the value exceeds &#x60;1000&#x60;, the default value of &#x60;25&#x60; will be used instead.
  # @return [TagsResponseBody]
  describe 'list_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for read_tag
  # Read tag
  # Use this endpoint to read the attributes of a particular tag according to its unique GUID.
  # @param tag_guid The unique id for a &#x60;tag&#x60;.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [TagResponseBody]
  describe 'read_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_tag
  # Update tag
  # Use this endpoint to update the name of a specific tag according to its unique GUID.
  # @param tag_guid The unique id for a &#x60;tag&#x60;.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param tag_update_request_body Tag object to be updated with required parameter (tag_guid)
  # @param [Hash] opts the optional parameters
  # @return [TagResponseBody]
  describe 'update_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
