=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

The version of the OpenAPI document: 20111101

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MxPlatformRuby::VerifiableCredentialsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VerifiableCredentialsApi' do
  before do
    # run before each test
    @api_instance = MxPlatformRuby::VerifiableCredentialsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VerifiableCredentialsApi' do
    it 'should create an instance of VerifiableCredentialsApi' do
      expect(@api_instance).to be_instance_of(MxPlatformRuby::VerifiableCredentialsApi)
    end
  end

  # unit tests for get_accounts_data
  # Get Accounts Data
  # Get an MX-issued verifiable credential of a user&#39;s accounts data.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param member_guid The unique id for a &#x60;member&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [VCResponse]
  describe 'get_accounts_data test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_identity_data
  # Get Identity Data
  # Get an MX-issued verifiable credential of a user&#39;s identity data.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param member_guid The unique id for a &#x60;member&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [VCResponse]
  describe 'get_identity_data test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_transactions_data
  # Get Transactions Data
  # Get an MX-issued verifiable credential of a user&#39;s transaction data.
  # @param user_guid The unique identifier for a &#x60;user&#x60;, beginning with the prefix &#x60;USR-&#x60;.
  # @param account_guid The unique id for an &#x60;account&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_time Filter transactions from this date. Must be in the format YYYY-MM-DD. The range is limited to 1 year.
  # @option opts [String] :end_time Filter transactions to this date. Must be in the format YYYY-MM-DD. The range is limited to 1 year.
  # @return [VCResponse]
  describe 'get_transactions_data test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
