=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

The version of the OpenAPI document: 20111101

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'date'
require 'time'

module MxPlatformRuby
  class ACHResponse
    attr_accessor :account_guid

    attr_accessor :account_number_last_four

    attr_accessor :account_type

    attr_accessor :ach_initiated_at

    attr_accessor :client_guid

    attr_accessor :corrected_account_number

    attr_accessor :corrected_routing_number

    attr_accessor :created_at

    attr_accessor :guid

    attr_accessor :id

    attr_accessor :institution_guid

    attr_accessor :investigation_notes

    attr_accessor :member_guid

    attr_accessor :processing_errors

    attr_accessor :resolution_code

    attr_accessor :resolution_detail

    attr_accessor :resolved_status_at

    attr_accessor :return_code

    attr_accessor :return_notes

    attr_accessor :return_account_number

    attr_accessor :return_routing_number

    attr_accessor :return_status

    attr_accessor :returned_at

    attr_accessor :sec_code

    attr_accessor :started_processing_at

    attr_accessor :submitted_at

    attr_accessor :transaction_amount

    attr_accessor :updated_at

    attr_accessor :user_guid

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_guid' => :'account_guid',
        :'account_number_last_four' => :'account_number_last_four',
        :'account_type' => :'account_type',
        :'ach_initiated_at' => :'ach_initiated_at',
        :'client_guid' => :'client_guid',
        :'corrected_account_number' => :'corrected_account_number',
        :'corrected_routing_number' => :'corrected_routing_number',
        :'created_at' => :'created_at',
        :'guid' => :'guid',
        :'id' => :'id',
        :'institution_guid' => :'institution_guid',
        :'investigation_notes' => :'investigation_notes',
        :'member_guid' => :'member_guid',
        :'processing_errors' => :'processing_errors',
        :'resolution_code' => :'resolution_code',
        :'resolution_detail' => :'resolution_detail',
        :'resolved_status_at' => :'resolved_status_at',
        :'return_code' => :'return_code',
        :'return_notes' => :'return_notes',
        :'return_account_number' => :'return_account_number',
        :'return_routing_number' => :'return_routing_number',
        :'return_status' => :'return_status',
        :'returned_at' => :'returned_at',
        :'sec_code' => :'sec_code',
        :'started_processing_at' => :'started_processing_at',
        :'submitted_at' => :'submitted_at',
        :'transaction_amount' => :'transaction_amount',
        :'updated_at' => :'updated_at',
        :'user_guid' => :'user_guid'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_guid' => :'String',
        :'account_number_last_four' => :'String',
        :'account_type' => :'String',
        :'ach_initiated_at' => :'String',
        :'client_guid' => :'String',
        :'corrected_account_number' => :'String',
        :'corrected_routing_number' => :'String',
        :'created_at' => :'String',
        :'guid' => :'String',
        :'id' => :'String',
        :'institution_guid' => :'String',
        :'investigation_notes' => :'String',
        :'member_guid' => :'String',
        :'processing_errors' => :'String',
        :'resolution_code' => :'String',
        :'resolution_detail' => :'String',
        :'resolved_status_at' => :'String',
        :'return_code' => :'String',
        :'return_notes' => :'String',
        :'return_account_number' => :'String',
        :'return_routing_number' => :'String',
        :'return_status' => :'String',
        :'returned_at' => :'String',
        :'sec_code' => :'String',
        :'started_processing_at' => :'String',
        :'submitted_at' => :'String',
        :'transaction_amount' => :'Float',
        :'updated_at' => :'String',
        :'user_guid' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'account_number_last_four',
        :'account_type',
        :'ach_initiated_at',
        :'corrected_account_number',
        :'corrected_routing_number',
        :'investigation_notes',
        :'processing_errors',
        :'resolution_code',
        :'resolution_detail',
        :'resolved_status_at',
        :'return_notes',
        :'return_account_number',
        :'return_routing_number',
        :'return_status',
        :'returned_at',
        :'sec_code',
        :'started_processing_at',
        :'submitted_at',
        :'transaction_amount',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MxPlatformRuby::ACHResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MxPlatformRuby::ACHResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_guid')
        self.account_guid = attributes[:'account_guid']
      end

      if attributes.key?(:'account_number_last_four')
        self.account_number_last_four = attributes[:'account_number_last_four']
      end

      if attributes.key?(:'account_type')
        self.account_type = attributes[:'account_type']
      end

      if attributes.key?(:'ach_initiated_at')
        self.ach_initiated_at = attributes[:'ach_initiated_at']
      end

      if attributes.key?(:'client_guid')
        self.client_guid = attributes[:'client_guid']
      end

      if attributes.key?(:'corrected_account_number')
        self.corrected_account_number = attributes[:'corrected_account_number']
      end

      if attributes.key?(:'corrected_routing_number')
        self.corrected_routing_number = attributes[:'corrected_routing_number']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'guid')
        self.guid = attributes[:'guid']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'institution_guid')
        self.institution_guid = attributes[:'institution_guid']
      end

      if attributes.key?(:'investigation_notes')
        self.investigation_notes = attributes[:'investigation_notes']
      end

      if attributes.key?(:'member_guid')
        self.member_guid = attributes[:'member_guid']
      end

      if attributes.key?(:'processing_errors')
        self.processing_errors = attributes[:'processing_errors']
      end

      if attributes.key?(:'resolution_code')
        self.resolution_code = attributes[:'resolution_code']
      end

      if attributes.key?(:'resolution_detail')
        self.resolution_detail = attributes[:'resolution_detail']
      end

      if attributes.key?(:'resolved_status_at')
        self.resolved_status_at = attributes[:'resolved_status_at']
      end

      if attributes.key?(:'return_code')
        self.return_code = attributes[:'return_code']
      end

      if attributes.key?(:'return_notes')
        self.return_notes = attributes[:'return_notes']
      end

      if attributes.key?(:'return_account_number')
        self.return_account_number = attributes[:'return_account_number']
      end

      if attributes.key?(:'return_routing_number')
        self.return_routing_number = attributes[:'return_routing_number']
      end

      if attributes.key?(:'return_status')
        self.return_status = attributes[:'return_status']
      end

      if attributes.key?(:'returned_at')
        self.returned_at = attributes[:'returned_at']
      end

      if attributes.key?(:'sec_code')
        self.sec_code = attributes[:'sec_code']
      end

      if attributes.key?(:'started_processing_at')
        self.started_processing_at = attributes[:'started_processing_at']
      end

      if attributes.key?(:'submitted_at')
        self.submitted_at = attributes[:'submitted_at']
      end

      if attributes.key?(:'transaction_amount')
        self.transaction_amount = attributes[:'transaction_amount']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'user_guid')
        self.user_guid = attributes[:'user_guid']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_guid == o.account_guid &&
          account_number_last_four == o.account_number_last_four &&
          account_type == o.account_type &&
          ach_initiated_at == o.ach_initiated_at &&
          client_guid == o.client_guid &&
          corrected_account_number == o.corrected_account_number &&
          corrected_routing_number == o.corrected_routing_number &&
          created_at == o.created_at &&
          guid == o.guid &&
          id == o.id &&
          institution_guid == o.institution_guid &&
          investigation_notes == o.investigation_notes &&
          member_guid == o.member_guid &&
          processing_errors == o.processing_errors &&
          resolution_code == o.resolution_code &&
          resolution_detail == o.resolution_detail &&
          resolved_status_at == o.resolved_status_at &&
          return_code == o.return_code &&
          return_notes == o.return_notes &&
          return_account_number == o.return_account_number &&
          return_routing_number == o.return_routing_number &&
          return_status == o.return_status &&
          returned_at == o.returned_at &&
          sec_code == o.sec_code &&
          started_processing_at == o.started_processing_at &&
          submitted_at == o.submitted_at &&
          transaction_amount == o.transaction_amount &&
          updated_at == o.updated_at &&
          user_guid == o.user_guid
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_guid, account_number_last_four, account_type, ach_initiated_at, client_guid, corrected_account_number, corrected_routing_number, created_at, guid, id, institution_guid, investigation_notes, member_guid, processing_errors, resolution_code, resolution_detail, resolved_status_at, return_code, return_notes, return_account_number, return_routing_number, return_status, returned_at, sec_code, started_processing_at, submitted_at, transaction_amount, updated_at, user_guid].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = MxPlatformRuby.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
