=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'date'
require 'time'

module MxPlatformRuby
  class MemberResponse
    attr_accessor :aggregated_at

    attr_accessor :background_aggregation_is_disabled

    attr_accessor :connection_status

    attr_accessor :guid

    attr_accessor :id

    attr_accessor :institution_code

    attr_accessor :is_being_aggregated

    attr_accessor :is_managed_by_user

    attr_accessor :is_manual

    attr_accessor :is_oauth

    attr_accessor :metadata

    attr_accessor :most_recent_job_detail_code

    attr_accessor :most_recent_job_detail_text

    attr_accessor :name

    attr_accessor :oauth_window_uri

    attr_accessor :successfully_aggregated_at

    attr_accessor :use_cases

    attr_accessor :user_guid

    attr_accessor :user_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'aggregated_at' => :'aggregated_at',
        :'background_aggregation_is_disabled' => :'background_aggregation_is_disabled',
        :'connection_status' => :'connection_status',
        :'guid' => :'guid',
        :'id' => :'id',
        :'institution_code' => :'institution_code',
        :'is_being_aggregated' => :'is_being_aggregated',
        :'is_managed_by_user' => :'is_managed_by_user',
        :'is_manual' => :'is_manual',
        :'is_oauth' => :'is_oauth',
        :'metadata' => :'metadata',
        :'most_recent_job_detail_code' => :'most_recent_job_detail_code',
        :'most_recent_job_detail_text' => :'most_recent_job_detail_text',
        :'name' => :'name',
        :'oauth_window_uri' => :'oauth_window_uri',
        :'successfully_aggregated_at' => :'successfully_aggregated_at',
        :'use_cases' => :'use_cases',
        :'user_guid' => :'user_guid',
        :'user_id' => :'user_id'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'aggregated_at' => :'String',
        :'background_aggregation_is_disabled' => :'Boolean',
        :'connection_status' => :'String',
        :'guid' => :'String',
        :'id' => :'String',
        :'institution_code' => :'String',
        :'is_being_aggregated' => :'Boolean',
        :'is_managed_by_user' => :'Boolean',
        :'is_manual' => :'Boolean',
        :'is_oauth' => :'Boolean',
        :'metadata' => :'String',
        :'most_recent_job_detail_code' => :'String',
        :'most_recent_job_detail_text' => :'String',
        :'name' => :'String',
        :'oauth_window_uri' => :'String',
        :'successfully_aggregated_at' => :'String',
        :'use_cases' => :'Array<String>',
        :'user_guid' => :'String',
        :'user_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'aggregated_at',
        :'connection_status',
        :'guid',
        :'id',
        :'institution_code',
        :'is_being_aggregated',
        :'is_managed_by_user',
        :'is_manual',
        :'is_oauth',
        :'metadata',
        :'most_recent_job_detail_code',
        :'most_recent_job_detail_text',
        :'name',
        :'oauth_window_uri',
        :'successfully_aggregated_at',
        :'use_cases',
        :'user_guid',
        :'user_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MxPlatformRuby::MemberResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MxPlatformRuby::MemberResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'aggregated_at')
        self.aggregated_at = attributes[:'aggregated_at']
      end

      if attributes.key?(:'background_aggregation_is_disabled')
        self.background_aggregation_is_disabled = attributes[:'background_aggregation_is_disabled']
      end

      if attributes.key?(:'connection_status')
        self.connection_status = attributes[:'connection_status']
      end

      if attributes.key?(:'guid')
        self.guid = attributes[:'guid']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'institution_code')
        self.institution_code = attributes[:'institution_code']
      end

      if attributes.key?(:'is_being_aggregated')
        self.is_being_aggregated = attributes[:'is_being_aggregated']
      end

      if attributes.key?(:'is_managed_by_user')
        self.is_managed_by_user = attributes[:'is_managed_by_user']
      end

      if attributes.key?(:'is_manual')
        self.is_manual = attributes[:'is_manual']
      end

      if attributes.key?(:'is_oauth')
        self.is_oauth = attributes[:'is_oauth']
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'most_recent_job_detail_code')
        self.most_recent_job_detail_code = attributes[:'most_recent_job_detail_code']
      end

      if attributes.key?(:'most_recent_job_detail_text')
        self.most_recent_job_detail_text = attributes[:'most_recent_job_detail_text']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'oauth_window_uri')
        self.oauth_window_uri = attributes[:'oauth_window_uri']
      end

      if attributes.key?(:'successfully_aggregated_at')
        self.successfully_aggregated_at = attributes[:'successfully_aggregated_at']
      end

      if attributes.key?(:'use_cases')
        if (value = attributes[:'use_cases']).is_a?(Array)
          self.use_cases = value
        end
      end

      if attributes.key?(:'user_guid')
        self.user_guid = attributes[:'user_guid']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          aggregated_at == o.aggregated_at &&
          background_aggregation_is_disabled == o.background_aggregation_is_disabled &&
          connection_status == o.connection_status &&
          guid == o.guid &&
          id == o.id &&
          institution_code == o.institution_code &&
          is_being_aggregated == o.is_being_aggregated &&
          is_managed_by_user == o.is_managed_by_user &&
          is_manual == o.is_manual &&
          is_oauth == o.is_oauth &&
          metadata == o.metadata &&
          most_recent_job_detail_code == o.most_recent_job_detail_code &&
          most_recent_job_detail_text == o.most_recent_job_detail_text &&
          name == o.name &&
          oauth_window_uri == o.oauth_window_uri &&
          successfully_aggregated_at == o.successfully_aggregated_at &&
          use_cases == o.use_cases &&
          user_guid == o.user_guid &&
          user_id == o.user_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [aggregated_at, background_aggregation_is_disabled, connection_status, guid, id, institution_code, is_being_aggregated, is_managed_by_user, is_manual, is_oauth, metadata, most_recent_job_detail_code, most_recent_job_detail_text, name, oauth_window_uri, successfully_aggregated_at, use_cases, user_guid, user_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = MxPlatformRuby.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
