=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MxPlatformRuby::AccountCreateRequestBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MxPlatformRuby::AccountCreateRequestBody do
  let(:instance) { MxPlatformRuby::AccountCreateRequestBody.new }

  describe 'test an instance of AccountCreateRequestBody' do
    it 'should create an instance of AccountCreateRequestBody' do
      expect(instance).to be_instance_of(MxPlatformRuby::AccountCreateRequestBody)
    end
  end
  describe 'test attribute "account"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
