=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MxPlatformRuby::RewardResponseBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MxPlatformRuby::RewardResponseBody do
  let(:instance) { MxPlatformRuby::RewardResponseBody.new }

  describe 'test an instance of RewardResponseBody' do
    it 'should create an instance of RewardResponseBody' do
      expect(instance).to be_instance_of(MxPlatformRuby::RewardResponseBody)
    end
  end
  describe 'test attribute "reward"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
