=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

The version of the OpenAPI document: 20111101

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MxPlatformRuby::TransactionIncludesResponseAllOfClassification
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MxPlatformRuby::TransactionIncludesResponseAllOfClassification do
  let(:instance) { MxPlatformRuby::TransactionIncludesResponseAllOfClassification.new }

  describe 'test an instance of TransactionIncludesResponseAllOfClassification' do
    it 'should create an instance of TransactionIncludesResponseAllOfClassification' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(MxPlatformRuby::TransactionIncludesResponseAllOfClassification)
    end
  end

  describe 'test attribute "parent_class"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Payroll", "Deposit", "Savings", "Transfer", "Refunds", "Spend", "Investment", "Buy", "Sell", "Income", "Fees", "Expenses", "Corporate Actions", "Other"])
      # validator.allowable_values.each do |value|
      #   expect { instance.parent_class = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "guid"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
