=begin
#MX Platform API

#The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

The version of the OpenAPI document: 20111101

Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MxPlatformRuby::UsersResponseBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MxPlatformRuby::UsersResponseBody do
  let(:instance) { MxPlatformRuby::UsersResponseBody.new }

  describe 'test an instance of UsersResponseBody' do
    it 'should create an instance of UsersResponseBody' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(MxPlatformRuby::UsersResponseBody)
    end
  end

  describe 'test attribute "users"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "pagination"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
