name: Automatic Tagging

on:
  push:
    branches: [master]

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.TAG_AND_RELEASE_TOKEN }}"
        commit_message_template: "({{number}} {{message}})"
        tag_prefix: "v"
        root: $GITHUB_WORKSPACE/lib/mx-platform-ruby/version.rb
        regex_pattern: "VERSION = '[0-9\\.]+'"
