name: Automatic Tagging

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.TAG_AND_RELEASE_TOKEN }}"
        commit_message_template: "({{number}} {{message}})"
        tag_prefix: "v"
        strategy: regex
        root: "/lib/mx-platform-ruby/version.rb"
        regex_pattern: "[\d.]+"
