name: Ruby

on: [push, pull_request]

jobs:
  validate_openapi:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run RuboCop and RSpec
      run: bundle exec rake
